### ISSUE TITLE
Runtime cache of initial route

### ISSUE THREAD

**Issue by gerhardsletten** [hanford/next-offline#8] opened 2018-02-23 22:36 UTC
Hi @hanford 

I am trying out this plugin, and its great that is caches all js-files, but still the issue with runtime cache of initial route is present. 

It's the old story about a user that visit your homepage, navigate to  sub-page and then leaves. If he never navigate back to your homepage, he will later get the chome-dino if he (while offline) try to visit your homepage.

Do you have any thoughts about this, or is this a user-land problem? What I did in my approach was to add a custom-script to the sw-precache which I from frontend could call a [method in the service-worker that added the pathname to manually cached](https://github.com/gerhardsletten/metabits-frontend/blob/master/pages/_document.js#L48)

**Comment by hanford** [comment] 2018-02-26 18:18
@gerhardsletten interesting, will hopefully have some time to take a look today.

**Comment by gerhardsletten** [comment] 2018-02-27 08:19
@hanford For initial route-caching I think it has to go into the runtime caching, but it looks like the the method for manually caching of an url is not supported in workbox 3.x, [see this issue](https://github.com/GoogleChrome/workbox/issues/807)

**Comment by hanford** [comment] 2018-03-01 22:32
interesting @gerhardsletten. So we're generating a service-worker using the `GenerateSW` webpack-loader from google that can be seen over [here](https://developers.google.com/web/tools/workbox/modules/workbox-webpack-plugin) I then wrote another custom webpack loader that will grab all the assets after build and generate a list like the one below:
```
self.__precacheManifest = [
  {
    "url": "/_next/eb4346f9-02a6-4db0-992f-ad74aa63e37e/page/_error.js",
    "revision": "eb4346f9-02a6-4db0-992f-ad74aa63e37e"
  },
  {
    "url": "/_next/eb4346f9-02a6-4db0-992f-ad74aa63e37e/page/chirp.js",
    "revision": "eb4346f9-02a6-4db0-992f-ad74aa63e37e"
  },
  {
    "url": "/_next/eb4346f9-02a6-4db0-992f-ad74aa63e37e/page/fast-flix.js",
    "revision": "eb4346f9-02a6-4db0-992f-ad74aa63e37e"
  },
  {
    "url": "/_next/eb4346f9-02a6-4db0-992f-ad74aa63e37e/page/index.js",
    "revision": "eb4346f9-02a6-4db0-992f-ad74aa63e37e"
  },
  {
    "url": "/_next/eb4346f9-02a6-4db0-992f-ad74aa63e37e/page/instachrome.js",
    "revision": "eb4346f9-02a6-4db0-992f-ad74aa63e37e"
  },
  {
    "url": "/_next/eb4346f9-02a6-4db0-992f-ad74aa63e37e/page/projects.js",
    "revision": "eb4346f9-02a6-4db0-992f-ad74aa63e37e"
  },
  {
    "url": "/_next/eb4346f9-02a6-4db0-992f-ad74aa63e37e/page/snapchat.js",
    "revision": "eb4346f9-02a6-4db0-992f-ad74aa63e37e"
  },
  {
    "url": "/_next/eb4346f9-02a6-4db0-992f-ad74aa63e37e/page/uber-chrome.js",
    "revision": "eb4346f9-02a6-4db0-992f-ad74aa63e37e"
  },
  {
    "url": "/_next/eb4346f9-02a6-4db0-992f-ad74aa63e37e/page/youtube-darkmode.js",
    "revision": "eb4346f9-02a6-4db0-992f-ad74aa63e37e"
  }
]
```

Next.js does some funny stuff with moving assets around where we need to do some crazy path reconciliation by the end of it.

Anyways, I'm wondering if we could make an addition to my code that generated the above list adds either `app.js` or `/` or something. I'm betting what is happening is the blanket runtime cache of anything served over `https` catches the initial route on the second visit but not the first.

Thoughts?

Also, sorry for the delay - really busy at work.

**Comment by gerhardsletten** [comment] 2018-03-01 23:22
After how I understand a service-worker it needs to be installed before it can cache additional resources (that is not defined to be precached), and I guess workbox does not have any magic solution for that. 

My approach was to create a NextAssets component with a render-callback that I would use in my _document.js override in order to expose which js and img resources needed for the initial route, and then I would post this to custom service-worker that would manually add these files to runtime cache.

The workbox-devs have [replied to the thread on how to manually cache a resource](https://github.com/GoogleChrome/workbox/issues/807#issuecomment-368968043) so I will try to upgrade to workbox from precache with that when I have time.

**Comment by elsigh** [comment] 2018-07-12 17:52
Looks like they closed that issue and provided an example? Maybe that would be feasible to incorporate?

**Comment by hanford** [comment] 2018-07-13 06:55
PR would be super helpful @elsigh, I am pretty swamped right now! (job transition)

**Comment by lasersox** [comment] 2018-10-03 05:13
I was able to hack statically generated next.js pages into the service worker generated by the plugin, just by manually adding them to precache. I haven't figured out how to solve the routing problem. workbox.routing defines this 'registerNavigationRoute' but I wasn't able to get it working so far.

**Comment by lasersox** [comment] 2018-10-03 06:45
Oh! Actually, adding this solved my problem:

```workboxOpts: {
    navigateFallback: "/",
  },```

**Comment by hanford** [comment] 2018-10-03 21:50
ahhh, so adding that precaches the initial route? It might make sense for me to add that as a default.

Can you confirm @gerhardsletten?

thanks @lasersox !

**Comment by lasersox** [comment] 2018-10-03 22:00
I think the base route is always pre-cached, even with default settings. Eg, when I visit the root of my website without this setting, it works as intended. But if I try to reload any other path while offline, I would get an error.

This setting configures the service-worker to serve up the "/" route in the event of no network access. It's still not perfect—a refresh on `/mypage` will render the `/` page even though the URL still shows `/mypage`. But it's better than an error state.

It could probably be resolved by adding more routes to the service worker, or by adding some logic in ComponentDidMount which calls router.push to update the app state after a refresh. I think I'm going to try the second option. One thing I realized is that `next export` is more intended for creating statically rendered sites than for creating PWAs. My site isn't really statically rendered—it uses indexeddb as a database and is dynamic works offline.

In case you are interested

https://tabsavior.com
https://github.com/lasersox/tabsavior

**Comment by srosset81** [comment] 2019-04-08 06:21
Hi @lasersox I think you may be interested in this issue I opened: https://github.com/hanford/next-offline/issues/128
Did you come up with a solution on your own ?

**Closed** 2020-06-01 05:22 UTC
