### ISSUE TITLE
File with name as given in swDest not created in case of custom service-worker

### ISSUE THREAD

**Issue by gauravdhiman** [hanford/next-offline#94] opened 2018-12-05 07:54 UTC
I am trying to have custom service-worker in my Next app to have web push capability. What I am observing is with below `next.config.js`

```js
const { join } = require('path');
const withOffline = require('next-offline');

module.exports = withOffline({
  generateSw: false,
  workboxOpts: {
    swSrc: join(__dirname, 'sw.js'),
    globPatterns: ['static/**/*'],
    globDirectory: '.'
  }
})
``` 
the `service-worker.js` does not get created in `.next` (build) folder. As per [this](https://developers.google.com/web/tools/workbox/modules/workbox-webpack-plugin#full_injectmanifest_config) `swDest` is defaulted to `service-worker.js` and should have been created.

When I run `next build client` command (my front-end code is in `client` folder) on terminal, I get an error `Error: ENOENT: no such file or directory, open 'C:\cygwin\home\gauravdhiman\proj\node\feathersjs\trackitt-pwa\client\.next\service-worker.js'`. Below is the complete output:
```
clean-webpack-plugin: C:\cygwin\home\gauravdhiman\proj\node\feathersjs\trackitt-pwa\client\.next\precache-manifest.*.js has been removed.
(node:13444) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
[00:25:49] Compiling server
[00:25:49] Compiling client
[00:25:54] Compiled server in 5s
[00:26:02] Compiled client in 12s
(node:13444) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'C:\cygwin\home\gauravdhiman\proj\node\feathersjs\trackitt-pwa\client\.next\service-worker.js'
(node:13444) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an
async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:13444) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

After `next build client` completes, below are the files under `.next` folder:
![image](https://user-images.githubusercontent.com/5612223/49497836-978f5980-f826-11e8-8923-52adaaf6e70d.png)

Here is the code of `sw.js`:
```js
self.addEventListener('push', (event) => {
  const title = 'Get Started With Workbox';
  const options = {
    body: event.data.text()
  };
  event.waitUntil(self.registration.showNotification(title, options));
});

workbox.precaching.precacheAndRoute(self.__precacheManifest);
```

Am I missing some config settings for `next-offline` due to which it is not working ?

**Comment by hanford** [comment] 2018-12-06 16:32
can you create a small repo where this issue is reproducible? That will help me dig a little deeper.

Thanks!

**Comment by PatrickSachs** [comment] 2018-12-06 21:02
I'm having an error that is probably related to the same cause. This config:

```js
  // Service Worker
  dontAutoRegisterSw: true,
  generateSw: false,
  workboxOpts: {
    swDest: path.join(__dirname, "./.build/sw/service-worker.js"),
    swSrc: path.join(__dirname, "./src/service-worker/index.js"),
    importWorkboxFrom: "local",
    globPatterns: ['static/**/*'],
    globDirectory: '.',
    //runtimeCaching: [{ urlPattern: /^https?.*/, handler: 'networkFirst' }],
  },
```
Throws this error `(node:2881) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/home/patrick/Development/helios/git/src/home/patrick/Development/helios/git/.build/home/patrick/Development/helios/git/.build/sw/service-worker.js'`.

This is caused by https://github.com/PatrickSachs/next-offline/blob/master/next-manifest.js#L21 - Both `options.outputPath` & `options.swDest` are absolute paths, so they just get appended to each other.

**Comment by hanford** [comment] 2018-12-07 17:00
@PatrickSachs we could probably have some code around this use case with a warning or something.

I'd be happy to merge a PR ¯\_(ツ)_/¯

**Comment by gauravdhiman** [comment] 2018-12-07 17:15
@hanford I will soon share a test repo where to reproduce this issue.
For now, I resolved the issue by auto-generating the service-worker and then injecting the web-push specific code in it using `importScript()` as mentioned in [this](https://github.com/hanford/next-offline/issues/35) .. that is working fine.

**Comment by hanford** [comment] 2018-12-09 23:56
@PatrickSachs can we close this now that #96 is merged?

**Comment by PatrickSachs** [comment] 2018-12-10 20:39
I'm not sure if my PR fixed this issue, it was just related to it. But if @gauravdhiman is happy with his solution I see no issue with closing this.

**Comment by wilsonpage** [comment] 2019-04-02 11:38
Just lost a lot of time on this, https://github.com/hanford/next-offline/issues/94#issuecomment-445028488 helped me get a working build.

I have a feeling not all config errors from `InjectManifest` are being surfaced. Or maybe `workbox-webpack-plugin` isn't failing silently 🤔For example, if I accidentally include `workboxOpts.runtimeCaching`, it also silently fails.

**Closed** 2020-06-01 05:22 UTC
