### ISSUE TITLE
Failing lighthouse audit with stock configuration

### ISSUE THREAD

**Issue by GusRuss89** [hanford/next-offline#134] opened 2019-05-06 06:18 UTC
I am using the stock-standard next-offline setup. server.js is copied straight from the now v1 example (I'm not using now), next.config.js exports the wrapped config, but doesn't add anything custom to it (no `workboxOpts`), and I have a manifest.json with the `start_url` set to `/`. My `npm run dev` and `npm start` scripts are updated to run `node server.js`. My app runs at `localhost:3000` (not a subdirectory).

When I run `npm run build` and then `npm start`, I can see that the service worker is successfully registered. However, when I run a lighthouse audit, I fail this rule:

> Does not register a service worker that controls page and start_url

I can see that the service worker is caching everything in my `/static` folder, as well as the following:

```
{
    "url": "/_next/static/runtime/main-6d31a0ae74beef7a4022.js"
  },
  {
    "url": "/_next/static/Xy2e1GQ9gG7-qnBaoY4si/pages/new-account/settings.js"
  },
  {
    "url": "/_next/static/Xy2e1GQ9gG7-qnBaoY4si/pages/re-enter-password.js"
  },
  {
    "url": "/_next/static/runtime/webpack-a79426b5e11f0ba5879d.js"
  },
  {
    "url": "/_next/static/Xy2e1GQ9gG7-qnBaoY4si/pages/send-receive.js"
  },
  {
    "url": "/_next/static/Xy2e1GQ9gG7-qnBaoY4si/pages/new-account/vault.js"
  },
  {
    "url": "/_next/static/chunks/commons.c1008a11b7593a069c2b.js"
  },
  {
    "url": "/_next/static/Xy2e1GQ9gG7-qnBaoY4si/pages/settings.js"
  },
  {
    "url": "/_next/static/Xy2e1GQ9gG7-qnBaoY4si/pages/_error.js"
  },
  {
    "url": "/_next/static/Xy2e1GQ9gG7-qnBaoY4si/pages/new-account/create-import.js"
  },
  {
    "url": "/_next/static/Xy2e1GQ9gG7-qnBaoY4si/pages/new-account.js"
  },
  {
    "url": "/_next/static/Xy2e1GQ9gG7-qnBaoY4si/pages/login.js"
  },
  {
    "url": "/_next/static/Xy2e1GQ9gG7-qnBaoY4si/pages/loading.js"
  },
  {
    "url": "/_next/static/Xy2e1GQ9gG7-qnBaoY4si/pages/index.js"
  },
  {
    "url": "/_next/static/Xy2e1GQ9gG7-qnBaoY4si/pages/email-verification.js"
  },
  {
    "url": "/_next/static/Xy2e1GQ9gG7-qnBaoY4si/pages/accounts.js"
  },
  {
    "url": "/_next/static/Xy2e1GQ9gG7-qnBaoY4si/pages/_app.js"
  }
```

I note that everything in that list is a `.js` file - there is no `/`, `/login` etc. Could that be my issue? Do I need to add some custom workbox configuration?

TIA

**Comment by hanford** [comment] 2019-05-06 17:15
Could you share a repo where this issue is reproducible? I have [this project](https://github.com/hanford/trends) which uses `next-offline` and scores a perfect performance audit in chrome, so the behavior you're experiencing is definitely not what should be happening

**Comment by GusRuss89** [comment] 2019-05-07 00:01
I'll make some time to put together a repro, but a couple of quick questions:

1. does the list of URLs look right, or should it have routes like `/` and `/login`?
1. just confirming - this should work with a regular SSR app and not only with `next export` right?

Thanks

**Comment by hanford** [comment] 2019-05-07 00:19
correct, none of my apps use `next export` and yes the URLs look correct

**Comment by lednhatkhanh** [comment] 2019-05-07 16:40
Also happens for me when using custom express config:

next.config.js

```javascript
/* eslint-disable @typescript-eslint/no-var-requires */
const withTypescript = require('@zeit/next-typescript');
const ForkTsCheckerWebpackPlugin = require('fork-ts-checker-webpack-plugin');
const dotenv = require('dotenv');
const nextOffline = require('next-offline');

dotenv.config();

module.exports = nextOffline(
  withTypescript({
    workboxOpts: {
      runtimeCaching: [
        {
          urlPattern: /^https:\/\/fonts\.gstatic\.com/,
          handler: 'cacheFirst',
        },
        {
          urlPattern: /^https:\/\/images\.unsplash\.com/,
          handler: 'cacheFirst',
        },
      ],
    },
    webpack(config, options) {
      // Do not run type checking twice:
      if (options.isServer) config.plugins.push(new ForkTsCheckerWebpackPlugin());

      return config;
    },
    env: {
      UNSPLASH_ACCESS_KEY: process.env.UNSPLASH_ACCESS_KEY,
      UNSPLASH_SECRET: process.env.UNSPLASH_SECRET,
      UNSPLASH_SCOPE: process.env.UNSPLASH_SCOPE,
      UNSPLASH_REDIRECT_URL: process.env.UNSPLASH_REDIRECT_URL,
    },
  }),
);
```

server.ts
```
server.get('/service-worker.js', (req, res) => {
    const filePath = path.join(__dirname, '..', 'service-worker.js');
    return app.serveStatic(req, res, filePath);
  });
```

The `service-worker.js` is loaded and working, but my website still fails the audit, I don't see the `Client` field in Chrome Devtools either.

I think either I'm doing wrong somewhere, or there is some problems when using custom server...

**Comment by lednhatkhanh** [comment] 2019-05-07 16:46
Wow, after adding `{ urlPattern: /^https?.*/, handler: 'networkFirst' }` all the audits passed!

**Comment by GusRuss89** [comment] 2019-05-08 01:29
This worked for me too. Any idea why it was necessary?

**Comment by hanford** [comment] 2019-05-09 00:06
@GusRuss89 when you pass a custom `runtimeCaching` arg in, it replaces the default. The default is `{ urlPattern: /^https?.*/, handler: 'networkFirst' }` which means cache everything served over https.

Were you overriding this property?

Going to go ahead and close this issue as this seems to be resolved.

**Closed by hanford** 2019-05-09 00:06 UTC
