### ISSUE TITLE
Not working when I deploy

### ISSUE THREAD

**Issue by lonelydatum** [hanford/next-offline#107] opened 2018-12-31 22:41 UTC
Hello, 

Thanks for the great library. I was able to get a simple create-next-app working and deployed with now.  

I used your **server.js** from here:
https://github.com/hanford/next-offline/blob/master/tests/server.js

**next.config.js**
const withOffline = require('next-offline')
module.exports = withOffline()

I took the the code from server.js and next.config.js to my real project. 
When I npm run build and npm run start it works offline. 

However, when I tried deployed it doesn't work offline. See url https://prequilt-offline.now.sh

From the console, I'm able to see the ServiceWorkerRegistration object and it even has the https://prequilt-offline.now.sh/service-worker.js

At this point I'm really stuck and need some help pointing me in the right direction. 

Any help would be much appreciated. 

Gar

**Comment by hanford** [comment] 2019-01-01 03:11
Any idea if it’s a now 1.0 or now 2.0 deployment? The two work pretty differently and thus require some different configurations.

If you post the code in a repo, I’d be happy to dig deeper

**Comment by lonelydatum** [comment] 2019-01-01 04:57
I'm using now 1.0
I've stripped down my app to just the landing page so it's not so overwhelming. The repo is here:
https://github.com/lonelydatum/prequilt_offline

I've also deployed version here:
https://prequilt-offline.now.sh

Any help would mean a lot to me. Thanks so much!

**Comment by hanford** [comment] 2019-01-01 12:03
@lonelydatum it actually is working offline, you usually need to go to the deployment once, so the SW can register and then when subsequent visits would work offline.

You can tell by going to `https://prequilt-offline.now.sh/` opening the console, disabling a network connection and reloading.

Going to go ahead and close this because i think things are working as intended.

**Closed by hanford** 2019-01-01 12:03 UTC

**Comment by lonelydatum** [comment] 2019-01-01 14:37
@hanford I disabled the network but it doesn't work. I've made a screen recording to show you.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/858774/50573803-aa0a9d80-0da8-11e9-84d4-d249ba897f12.gif)


Does it work for you?

**Comment by hanford** [comment] 2019-01-03 03:15
@lonelydatum it looks like you’re testing when the service worker itself isn’t “online”. I think this is different than network status.

To test you, can disable your network connection and you’ll see your website still works while offline

**Comment by lonelydatum** [comment] 2019-01-03 18:10
Oh man, so embarrassing. 
Wow. I turned off my wifi and it works.

**Comment by hanford** [comment] 2019-01-03 22:31
@lonelydatum no worries! Open another issue if you run into anything else
