### ISSUE TITLE
A bad HTTP response code (404) was received when fetching the script.

### ISSUE THREAD

**Issue by heshamelmasry77** [hanford/next-offline#141] opened 2019-05-16 13:38 UTC
A bad HTTP response code (404) was received when fetching the script.

Error during worker registration: TypeError: Failed to register a ServiceWorker: A bad HTTP response code (404) was received when fetching the script.

i am trying to add PWA to my next js app but it is not registering.

this is my next.config.js

```
const withImages = require('next-images');
const withFonts = require('next-fonts');
const withCss = require('@zeit/next-css');
const withSass = require('@zeit/next-sass');
const webpack = require('webpack');
const path = require('path');
const FilterWarningsPlugin = require('webpack-filter-warnings-plugin');
const TerserPlugin = require('terser-webpack-plugin');
const withOffline = require('next-offline');

require('dotenv').config();
const dotenv = require('dotenv');
const nextConfig = {
  // Service Worker
  generateSw: false,
  devSwSrc: path.join(__dirname, "./utils/serviceWorker/sw.js"),
  workboxOpts: {
    swDest: "./service-worker.js",
    swSrc: path.join(__dirname, "./utils/serviceWorker/sw.js"),
    globPatterns: ["**/*.{ico,html,js,json}"],
    globDirectory: "./_next/static",
    runtimeCaching: [
      {
        urlPattern: /^https?.*/,
        handler: 'networkFirst',
        options: {
          cacheName: 'https-calls',
          networkTimeoutSeconds: 15,
          expiration: {
            maxEntries: 150,
            maxAgeSeconds: 30 * 24 * 60 * 60 // 1 month
          },
          cacheableResponse: {
            statuses: [0, 200]
          }
        }
      }
    ]
  }
};

// console.log(process.env.REACT_APP_REST_API_LOCATION);
module.exports = withImages(withFonts(withCss(withSass(withOffline({
  webpack: (config, {dev}) => {
    const env = dotenv.config().parsed;

    // reduce it to a nice object, the same as before
    const envKeys = Object.keys(env).reduce((prev, next) => {
      prev[`process.env.${next}`] = JSON.stringify(env[next]);
      return prev;
    }, {});

    const oldEntry = config.entry;
    config.entry = () => oldEntry().then(entry => {
      if(entry['main.js'] !== undefined) {
        entry['main.js'].push(path.resolve('./utils/offline'));
      }
      return entry
    });
    if(!dev){
      config.optimization.minimizer = [new TerserPlugin({
        parallel: true,
        sourceMap: true
      })];
    }
    config.plugins.push(
        new webpack.EnvironmentPlugin(process.env)
    );

    const newConfig = { ...config };
    newConfig.plugins = [
      ...config.plugins,
      new FilterWarningsPlugin({
        exclude: /mini-css-extract-plugin[^]*Conflicting order between:/,
      }),
      new webpack.DefinePlugin(envKeys)
    ];
    return newConfig
  },
  nextConfig
})))));

```

and here is my server.js

```
const express = require('express');
const next = require('next');
const fs = require("fs");
const path = require('path');

const port = parseInt(process.env.PORT, 10) || 3000;
const dev = process.env.NODE_ENV !== 'production';
const app = next({ dev });
const handle = app.getRequestHandler();
const { DESTINATION, createSitemap } = require("./sitemap");
// Redirect all HTTP traffic to HTTPS
function ensureSecure(req, res, next){
  if(req.headers["x-forwarded-proto"] === "https"){
    // OK, continue
    return next();
  }
  res.redirect('https://'+req.hostname+req.url);
}
app.prepare().then(() => {
  const server = express();
  server.enable("trust proxy");
  // This `server.get()` lets you generate a sitemap on the fly and retrive it from http://your.domain/sitemap.xml
  // It also create a file if you need to open it with your editor.
  server.get("/sitemap.xml", function(req, res) {
    res.header("Content-Type", "application/xml");
    (async function sendXML() {
      let xmlFile = await createSitemap();
      // Send it to the browser
      res.send(xmlFile);
      // Create a file on the selected destination
      fs.writeFileSync(DESTINATION, xmlFile);
    })();
  });
  const robotsOptions = {
    root: __dirname + '/static/',
    headers: {
      'Content-Type': 'text/plain;charset=UTF-8',
    }
  };
  server.get('/robots.txt', (req, res) => (
      res.status(200).sendFile('robots.txt', robotsOptions)
  ));


  server.get('/service-worker.js', function(request, response) {
    response.sendFile(path.resolve(__dirname, '.next', 'service-worker.js'));
  });


// Handle environments
  if (process.env.NODE_ENV === 'production' && port !== 3000) {
    server.all('*', ensureSecure);
  }
  server.get('*', (req, res) => {
    return handle(req, res)
  });
  server.listen(port, err => {
    if (err) throw err
    console.log(`> Ready on http://localhost:${port}`)
  })
});

```

and this is my package.json 

```
{
  "name": "findaroome",
  "version": "1.0.0",
  "engines": {
    "node": "10.x"
  },
  "scripts": {
    "dev": "node server.js",
    "build": "yarn pretty && next build",
    "start": "NODE_ENV=production node server.js",
    "heroku-postbuild": "next build",
    "pretty": "prettier --single-quote --list-different --write --tab-width 2 \"components/**/*.js\" --tab-width 2 \"pages/**/*.js\" "
  },
  "dependencies": {
    "@firebase/app-types": "0.3.2",
    "@firebase/auth-types": "0.5.1",
    "@firebase/database-types": "0.3.2",
    "@firebase/util": "^0.2.7",
    "@zeit/next-css": "^1.0.1",
    "@zeit/next-sass": "^1.0.1",
    "axios": "^0.18.0",
    "cacheable-response": "^1.1.0",
    "calidation": "^1.7.0",
    "classnames": "^2.2.6",
    "delayed-scroll-restoration-polyfill": "^0.1.1",
    "dotenv": "^7.0.0",
    "express": "^4.14.0",
    "firebase": "^5.8.4",
    "formik": "^1.5.1",
    "get-google-fonts": "^1.2.0",
    "glob": "^7.1.3",
    "google-maps-react": "^2.0.2",
    "husky": "^1.3.1",
    "isomorphic-unfetch": "^3.0.0",
    "lodash": "^4.17.11",
    "memoize-one": "^5.0.0",
    "moment": "^2.18.1",
    "next": "latest",
    "next-compose-plugins": "^2.1.1",
    "next-fonts": "^0.17.0",
    "next-images": "^1.0.4",
    "next-offline": "^4.0.0",
    "node-sass": "^4.11.0",
    "preact": "^8.4.2",
    "prop-types": "^15.7.2",
    "react": "^16.7.0",
    "react-burger-menu": "^2.6.5",
    "react-currency-formatter": "^1.1.0",
    "react-dates": "^19.0.4",
    "react-dom": "^16.8.4",
    "react-dropzone": "^9.0.0",
    "react-icons": "^3.4.0",
    "react-image-gallery": "^0.8.14",
    "react-infinite-scroll-component": "^4.5.2",
    "react-input-range": "^1.3.0",
    "react-intl": "^2.8.0",
    "react-places-autocomplete": "^7.2.1",
    "react-responsive": "^6.1.1",
    "react-responsive-modal": "^3.6.0",
    "react-scroll": "^1.7.11",
    "react-switch": "^4.1.0",
    "react-transition-group": "^2.6.0",
    "react-with-direction": "^1.3.0",
    "responsive-loader": "^1.2.0",
    "styled-components": "^4.1.3",
    "styled-jsx-plugin-sass": "^1.0.0",
    "superagent": "^4.1.0",
    "terser-webpack-plugin": "^1.2.3",
    "webpack": "^4.29.6",
    "webpack-filter-warnings-plugin": "^1.2.1",
    "yup": "^0.26.10"
  },
  "devDependencies": {
    "babel-plugin-styled-components": "^1.10.0",
    "prettier": "^1.16.4"
  }
}

```

the problem that is not registering my service-worker.js

following this repo : https://github.com/hanford/next-offline-issue-127

i created a folder call serviceWorker inside the utiles folder and i have another sw.js file

**Comment by hanford** [comment] 2019-05-16 16:17
When you build your application does the service worker end up in `.next/service-worker`?

Why do you have this line in your next.config?

```
    const oldEntry = config.entry;
    config.entry = () => oldEntry().then(entry => {
      if(entry['main.js'] !== undefined) {
        entry['main.js'].push(path.resolve('./utils/offline'));
      }
      return entry
    });
```

Could you provide a repo where I can pull down and take a deeper look?

**Comment by heshamelmasry77** [comment] 2019-05-19 20:54
@hanford  i have added you to the project please do have a look :)

**Comment by programbo** [comment] 2019-05-22 04:35
@hanford Could the problem be that @heshamelmasry77 is using Next.js 8 and deploying to Now 2.0? The build will be done remotely so there is no opportunity to move the service-worker.js to somewhere accessible or route to it in now.json.

Is it possible to set a path to output the service worker? Like build it in `/static/service-worker.js` or move it there post-build?

**Comment by programbo** [comment] 2019-05-22 05:35
Disregard my idea. Turns out that moving the `service-worker.js` into `static` is simple with a `mv` command in the `now-build` task, but the service worker wants to reference things in the old Next 7 file structure.

**Comment by heshamelmasry77** [comment] 2019-05-22 08:48
@programbo Hey i actually don't use now 2 cause of the routing weird way they want us to implemented it. So i use heroku and normal express server. 
Regarding my issue yes it is still not working :( and i have no idea why this is happening.

**Comment by eltel** [comment] 2019-07-03 15:08
I'm having the same issue on Heroku using Express - was there any fix for this?? I'm attempting to add PWA functionality to an already existing NextJS app is why - I can't find instructions on how to do this - I'm not getting any errors except the standard:
`SW registration failed:  TypeError: Failed to register a ServiceWorker: A bad HTTP response code (404) was received when fetching the script.`

error.

If anyone can direct me to a solution or docs for adding offline/PWA to an existing nextJS app I'd appreciate it.

Thanks

Terry

**Comment by hanford** [comment] 2019-07-03 21:33
@eltel I bet this is wrong: https://github.com/eltel/portugles/blob/master/server/index.js#L66

In the example, it assumes you have a `server.js` in the root directory, in your case it looks like it's not in the root, but in a subdirectory.

Maybe try adding a `../` or something along those lines for the path

**Comment by heshamelmasry77** [comment] 2019-07-04 10:37
@hanford can you maybe give me some help in this cause i am still having the same issue as well.

**Comment by eltel** [comment] 2019-07-04 14:35
Hi @hanford   - thanks for your time - while your explanation makes sense to me, it's still not working, I've tried everything I can think of but it's still constantly throwing the same error - I'm trying to identify exactly what I need to add to a pre-existing nextjs application to enable the service worker - I think maybe adding/using 'createServer' to/in a pre-existing Express server was a boo-boo - forgive my ignorance but server-side code isn't my strong point.

Thanks

Terry

**Comment by heshamelmasry77** [comment] 2019-07-04 16:41
@programbo  i am using heroku cause i have problem with now 2 and the new ways of routing.

**Comment by serjt12** [comment] 2019-07-04 16:56
Guys, I have been dealing with the same error, and the way to fix it was, as @hanford recommended `../ `but like this: 
```
express.get('/service-worker.js', function(request, response) {
      response.sendFile(path.resolve(__dirname, '../.next', 'service-worker.js'));
    })
```
I hope this helps. regards.

**Comment by eltel** [comment] 2019-07-04 21:03
@serjt12  - Man, at first glance that appears to have worked!! I'll check in detail tomorrow (running short on time tonight) - many thanks, either way, I'll get back to you asap.

**Comment by eltel** [comment] 2019-07-04 22:19
So, thanks again @serjt12 - the service worker now seems to be registering correctly, although now I can't get the browser to fetch my web manifest, I've tried both site.manifest and manifest.json in the root directory and I keep getting a
 `This page is controlled by a service worker, however, no start_url was found because no manifest was fetched.` error (and similar) - I know this is not related, but could you tell me where your manifest is kept I'd appreciate it.

Thanks so much guys.

**Comment by hanford** [comment] 2019-07-10 20:16
@heshamelmasry77 are you still experiencing the issue?

**Comment by Vgurnani** [comment] 2019-07-24 12:26
@hanford I am facing the same issue. 
SW registration failed:  TypeError: Failed to register a ServiceWorker: A bad HTTP response code (404) was received when fetching the script.

I have built an app using a custom server.

server.js

const fs = require('fs')
const http = require('http')
const next = require('next')
const path = require('path')
const https = require('https')
const routes = require('./routes')
const express = require('express')
const compression = require('compression')
// Dot env
require('dotenv').config()

const config = {
  port: process.env.PORT || 3000
}

const dev = process.env.NODE_ENV !== 'production'
const app = next({ dir: '.', dev })
const handle = app.getRequestHandler()
const handler = routes.getRequestHandler(app)

let options = null

if (dev) {
  options = {
    key: fs.readFileSync('/Users/ibox/Desktop/localhost_certificates/cert.key'),
    cert: fs.readFileSync('/Users/ibox/Desktop/localhost_certificates/cert.crt')
  }
}

app.prepare().then(() => {
  const server = express()
  server.use(compression())
  server.use(handler)
  server.get('/service-worker.js', ServiceWorker(app))
  server.get('*', (req, res) => {
    return handle(req, res)
  })

  const httpPort = dev ? 5000 : config.port

  http.createServer(server).listen(httpPort, err => {
    if (err) throw err
    console.log(`> HTTP Ready on http://localhost:${httpPort}`)
  })

  if (dev) {
    https.createServer(options, server).listen(3000, err => {
      if (err) throw err
      console.log(`> HTTPS Ready on https://localhost:${config.port}`)
    })
  }
})

const ServiceWorker = app => (req, res) => {
  filePath = join(__dirname, '.next', 'service-worker.js')
  app.serveStatic(req, res, filePath)
}

My sw file named service-worker.js gets generated in .next folder, but it shows the error code mentioned above. Could you please help me out in this?

**Comment by serjt12** [comment] 2019-07-24 13:31
make sure to point to the correct path to your `.next` folder could be `../.next` depending on your folder structure.

**Comment by hanford** [comment] 2019-07-24 18:48
@Vgurnani it would also be helpful if you created a sample repository that reproduces this problem, I currently don't have enough information on solving your particular problem.

**Comment by davisbartce** [comment] 2019-08-23 05:06
https://github.com/davisbartce/next


Good night, How are you? I hope someone can help me, I have the same problem , but on my server nginx with pm2 for the nextjs application, but I can't find a solution, in NOW it works perfectly.
If it's any use and my site is in the following structure /var /www/html/nextjs.


this way I execute my project on the server:

sudo npm run build
sudo pm2 start npm --name "nextjs"  -- start

![image](https://user-images.githubusercontent.com/8561386/63567988-469cce00-c539-11e9-8a22-86dde1a98602.png)


and this is my configuration 

const withOffline = require('next-offline');

const nextConfig = {
    target: 'serverless',
    workboxOpts: {
        swDest: 'static/service-worker.js',
        runtimeCaching: [
            {
                urlPattern: /^https?.*/,
                handler: 'NetworkFirst',
                options: {
                    cacheName: 'https-calls',
                    networkTimeoutSeconds: 15,
                    expiration: {
                        maxEntries: 150,
                        maxAgeSeconds: 30 * 24 * 60 * 60, // 1 month
                    },
                    cacheableResponse: {
                        statuses: [0, 200],
                    },
                },
            },
        ],
    },
};

module.exports = withOffline(nextConfig);
----------------------------------------------------------
grateful in advance

**Comment by lookapanda** [comment] 2019-12-03 18:00
Why is this still an open issue? Is there no solution?

**Comment by skivol** [comment] 2020-05-17 17:02
> Guys, I have been dealing with the same error, and the way to fix it was, as @hanford recommended `../ `but like this:
> 
> ```
> express.get('/service-worker.js', function(request, response) {
>       response.sendFile(path.resolve(__dirname, '../.next', 'service-worker.js'));
>     })
> ```
> 
> I hope this helps. regards.

This helps, but apart from the path (in my case the `server.js` is in the root folder so it was `'./.next'`), note that `response.sendFile` is used and not `app.serveStatic` as in the `now1-example`, which probably doesn't work that well outside of `now` deployment scheme.

**Comment by heshamelmasry77** [comment] 2020-05-21 10:11
> @heshamelmasry77 are you still experiencing the issue?

yes it works now thank you.

**Comment by hanford** [comment] 2020-05-27 05:39
Can this issue be closed?

**Comment by hanford** [comment] 2020-05-27 05:41
@heshamelmasry77 @lookapanda going to go ahead and close this issue.

**Closed by hanford** 2020-05-27 05:41 UTC
