### ISSUE TITLE
webpackHotUpdate is not defined

### ISSUE THREAD

**Issue by raymondsze** [hanford/next-offline#121] opened 2019-02-26 16:10 UTC
Reference: https://github.com/zeit/next.js/issues/6168

I use next-offline with nextJs v7.0.2. After start my application in dev mode, there is `Uncaught ReferenceError: webpackHotUpdate is not defined` logged in console.

**Comment by hanford** [comment] 2019-02-27 16:56
Hmm, can you provide a repository where this issue is reproduceable?

**Comment by majongaagnojam** [comment] 2019-02-27 22:49
Hello,

I have the same error, plus this one :

`SW registration failed:  TypeError: Failed to register a ServiceWorker: A bad HTTP response code (404) was received when fetching the script.`

Here is my repo to reproduce : https://github.com/majongaagnojam/next

Thanks you !

**Comment by hanford** [comment] 2019-02-28 16:43
@majonga88 it looks like you've added next-offline to your `next.config` but you're not handling it on your server. (You need to ensure that your server knows to serve the webpack generated service worker)

In the next-offline documentation we specify how you can do this: https://github.com/hanford/next-offline#serving-service-worker

**Comment by hanford** [comment] 2019-02-28 16:48
@raymondsze I'm able to reproduce the issue you're describing in a repo I have locally. Hopefully will have some time to dive in over the next couple of days..

**Comment by hanford** [comment] 2019-02-28 18:00
@raymondsze this should be fixed in `next-offline v3.3.6` going to go ahead and close, thanks!

**Closed by hanford** 2019-02-28 18:00 UTC

**Comment by majonga88** [comment] 2019-02-28 20:32
It works and you fix it thanks a lot !

**Comment by raymondsze** [comment] 2019-03-04 09:20
It works now! thanks a lot.

**Comment by marcioj** [comment] 2019-03-21 14:21
Hi there! I see this error when using the `generateInDevMode: true` option. I believe it happens because this part is called multiple times https://github.com/hanford/next-offline/blob/0e10965ec052efe6bd71d594ce5fe9e337538746/index.js#L66 causing the file to be added multiple times.

Checking if the file is already there fixed the issue for me

```
        if (
          entries['main.js'] &&
          !entries['main.js'].includes(require.resolve('./register-sw-compiled.js')) &&
          !dontAutoRegisterSw
        ) {
```

Also looking the next with-polyfill example they handle it in the same way https://github.com/zeit/next.js/blob/canary/examples/with-polyfills/next.config.js#L9 so maybe it is fine to use this approach.
I will try to send a PR with those changes.
